Front to back connection
Tsunghao-C/ft_Transcendence pull request #30
Opened 2024-12-05 16:32 UTC by Atwazar

This pull request is updating the front with a fonction that is abble to fetch based on the JWT token
it will fectch data, if the JWT token is not on date anymore, it will make the refresh request to get a new one, then  it will try it again.

Tokens are stored in cookies now, as local storage is apparently not safe enough.

This commit is bypassing the 2FA security as the JWT token send by 2FA are not working or error is occuring in the backend.

Finally this commit starts to connect the dots, making a request in the loadpage function, and having some fetch function prepared for the apis

2024-12-06 07:43 UTC, BenjaminHThomas requested changes
We shouldn't be returning 200 "everything's good" when the function fails.

Instagram and other sites return 200 because they're serving a JSON payload that includes the actual status/error message.

2024-12-08 19:13 UTC, Atwazar commented
In this PR, the logic for friend is kinda done as well for the profile, 
there's still some redirection issues where the pages is not load automatically but the adress changes, 
to test it you can create multiple accounts via the front end and test to add them, view their profile and delete them, block them, or whatever ( as i said sometimes to go to a profile you have to load the address multiple times)
also when creating an account the error message might be displayed but the account is still created

2024-12-08 19:22 UTC, BenjaminHThomas commented on pong-game/game-service/app/user_service/views.py
> +		}, status=200)
this should be a get request not a post request.

2024-12-08 19:58 UTC, Atwazar commented
![image](https://github.com/user-attachments/assets/fcd68fe0-76b3-4374-99f7-929341f690f5)
![image](https://github.com/user-attachments/assets/97bfcc20-d34e-4bb8-bcb8-f0c883eea62a)
changed !

2024-12-08 20:17 UTC, BenjaminHThomas approved these changes
not sure how you managed to convince git that you changed every single line of the views.py, I'm impressed.

LGTM

2024-12-08 20:17 UTC, merged